version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    build:
      context: .
      dockerfile: "Dockerfile_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:4306'
    volumes:
      - ./data:/var/lib/mysql
volumes:
  mysql_vol:
    driver: local
