version: '3'
services:
  web:
    build:
      context: containers/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - tmp-data:/myapp/tmp
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/webapp
      - tmp-data:/myapp/tmp
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      CORS_ALLOWED_ORIGINS:
  db:
    build:
      context: .
      dockerfile: "Dockerfile_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:4306'
    volumes:
      - ./data:/var/lib/mysql
volumes:
  mysql_vol:
    driver: local
  tmp-data:
